### ISSUE TITLE
On agent restart, the first command in queues get lost

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/jsagentcontroller#1]
Scenario:
- Agent consumes cmds ...
- While agent on a long-poll (waiting state), agent is restarted
- Agent starts again and start polling.
- Send command on redis queue
- The command is lost and never delivered to the agent.

I think the reason for this is that when the agent restarted, the long poll on the AC side (the waiting co-routine) never exited. When the agent start polling again another co-routine was created on the AC side. So now we have 2 co-routines that are polling on the same queue.
When a command is pushed to the queue, the first co-routine consumes it and of course the command is lost because the agent is not actually receiving on this channel anymore.

I think the fix should be that when the actually HTTP connection is lost, the co-routine must cancel the queue waiting.

**Comment by maxux** [comment]
Seems to be a little more complex than expected, gin context seems to limit the access to the connection. I search a way to detect a connection reset.

**Comment by maxux** [comment]
Fixed with `c.Writer.(http.CloseNotifier).CloseNotify()` trick

**Comment by muhamadazmy** [comment]
This didn't fix the problem, the first command after the agent restart is always lost, because it's consumed by the dead client long poll.
